apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "riot.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ include "riot.name" . }}
data:
  config.json: |-
{{ .Files.Get "envfiles/config.json" | indent 4 }}